// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlxcbfgxmalqtvowgofx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpseGNiZmd4bWFscXR2b3dnb2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTQ3NjcsImV4cCI6MjA3MTgzMDc2N30.DMv-yGEBMv6scLayk6ax3SxKWNbBY2ZHaZHcR6RGzxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});